#AWS Access Key
AWS_ACCESS_KEY_ID = "AKIAIJV7FGJ2GVQRYEBQ"
#AWS Secret Key
AWS_SECRET_ACCESS_KEY = "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"
#EC2 SSH Key Name
AWS_SSH_KEY_NAME = "fastDataPlatform"
#AWS Region
AWS_DEFAULT_REGION = "us-east-1"
