
all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: centos
    ansible_become: true
    security_mode: plaintext
preflight:
  hosts:
    18.232.160.95:
    3.80.159.75:
    54.91.73.53:
    34.235.120.174:
ssl_CA:
  hosts:
    18.232.160.95:
zookeeper:
  hosts:
    18.232.160.95:
    3.80.159.75:
    54.91.73.53:
broker:
  hosts:
    18.232.160.95:
      kafka:
        broker:
          id: 1
    3.80.159.75:
      kafka:
        broker:
          id: 2
    54.91.73.53:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    18.232.160.95:
control-center:
  hosts:
    34.235.120.174 ansible_host:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: 18.232.160.95:8083
connect-distributed:
  hosts:
    18.232.160.95:
kafka-rest:
  hosts:
    18.232.160.95:
ksql:
  hosts:
    3.80.159.75:
